# Other Policies

These are things I must include in the syllabus in this format. If you have questions, email me.

## Statement on Disability

In accordance with federal law, if you have a documented disability, you may be eligible to request accommodations from Disability Resources. Students with a disability, please make an appointment with the instructor to discuss your needs at the earliest convenience. The necessary adjustments will be provided to facilitate the learning experience. Additionally, please be in contact with the Coordinator of Disability Resources, Educational Services for Students (ESS). ESS is located in 470 Sears Building. The office phone number is 216-368-5230, and the website is: <http://studentaffairs.case.edu/education/disability/policy.html>

Please keep in mind that accommodations are not retroactive.

## Incomplete Grades

The grade of Incomplete is assigned at the discretion of an instructor provided that:

1.	There are extenuating circumstances, explained to the instructor before the assignment of the grade, which clearly justify an extension of time beyond the requirements established for other students in the class. It is the student's responsibility to notify the instructor of the circumstances preventing completion.
2.	The student has been passing the course and only a small segment of the course remains to be completed, such as a term paper, for which the extenuating circumstances justify a special exception.

An Incomplete grade may not be assigned if a student is absent from a final examination, unless the dean has authorized the absence. Unauthorized absence from a final examination will result in a failing grade. When the student completes the work, the Incomplete is changed to an A, B, C, D, P, F, or NP.

All work for the incomplete grade must be made up and the change of grade recorded in the Office of the University Registrar by the date specified by the instructor, but no later than the last day of class in the semester following the one in which the Incomplete was received. A student who has a permanent Incomplete for a required course must retake the course in a later term. If the student cannot complete the work by the end of the following semester, he or she must petition for an extension which must be endorsed by the instructor, explain the reasons why the work has not been completed, and include a new date for completion. Students will be allowed only one extension of no more than one additional semester to complete the work for an Incomplete grade.

## Laptop and cell phone use 

Although having a laptop in class opens up new learning possibilities for students, it can be used in ways that are inappropriate. It is easy for your laptop to become a distraction to you and to those around you. Laptops are to be used only when essential to the task at hand.  Please turn off or silence all cell/smart phones, tablets, and other electronic devices for the duration of the course. Inappropriate uses will be noted and may affect the final grade.

## Diversity and Inclusion

It is the intent that all students regardless of their background and perspective be well-served by this class.  Further, we intend to present material whose content is respectful of diversity (gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture) and deliver it in a way that respects these differences as well.  We expect that all students, instructors and guests will help foster an atmosphere of respect, trust and safety in the classroom.  

If you have suggestions for how to make the class content or environment more inclusive, or have specific incidents to report, please reach out to the instructor.  If you are not comfortable reaching out to the instructor, feel free to reach out to someone else, such as the School of Medicine Graduate Education Office (som-geo@case.edu) or the Office of Inclusion, Diversity and Equal Opportunity (OIDEO) (oideo@case.edu).  

More information on University policy and resources are available on OIDEO’s website at https://case.edu/diversity/.

## Academic Integrity

Any violation of the University’s Code of Ethics will not be tolerated. All forms of academic dishonesty including cheating, plagiarism, misrepresentation, and obstruction are violations of academic integrity standards and will result in a minimum penalty of receiving a zero for the assignment, the potential for failing the entire course. Cheating includes copying from another's work, falsifying problem solutions or laboratory reports, or using unauthorized sources, notes or computer programs. Plagiarism includes the presentation, without proper attribution, of another's words or ideas from printed or electronic sources. It is also plagiarism to submit, without the instructor's consent, an assignment in one class previously submitted in another. Misrepresentation includes forgery of official academic documents, the presentation of altered or falsified documents or testimony to a university office or official, taking an exam for another student, or lying about personal circumstances to postpone tests or assignments. Obstruction occurs when a student engages in unreasonable conduct that interferes with another's ability to conduct scholarly activity. Destroying a student's computer file, stealing a student's notebook, and stealing a book on reserve in the library are examples of obstruction. 

In addition, the incident will be reported to the Dean of Undergraduate Studies and Academic Review Board for undergraduates or Senior Associate Dean of Graduate Studies, for Graduate Students. 

The CWRU Statement of Ethics for graduate students can be found here: 
<http://case.edu/gradstudies/about-the-school/policies-procedures/>

## Plagiarism

Unless specifically stated otherwise, the faculty of the PQHS expect and require original writing for all assignments given. Submitting plagiarized work for an academic requirement is a violation of the academic integrity standards set forth by the University. Plagiarism is the representation of another's work or ideas as one's own; it includes the unacknowledged, word-for-word use and/or paraphrasing of another person's work, and/or the inappropriate unacknowledged use of another person's ideas. Submitting substantially the same work to satisfy requirements for one course that has been submitted in satisfaction of requirements for another course, without permission of the instructor of the course for which the work is being submitted, is also prohibited.

